#!/usr/bin/env python3
#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause

"""Tests for the host-side survey decoder.

Two layers, and both matter:

- The golden-file tests decode the *exact bytes the firmware encoder produced*
  (tests/host/fixtures/, regenerated by scripts/survey_fixture.py). That is what proves
  encoder and decoder against each other rather than against two separate readings of
  the CDDL.
- The targeted tests assert specific values against the inputs the firmware test fed the
  encoder, so a golden file that is wrong in the same way as the code cannot pass
  silently.

Run with:  python3 -m unittest discover -s tests/host
"""

import json
import pathlib
import struct
import sys
import unittest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent.parent / "scripts"))

from survey_decode import (  # noqa: E402
    CborError,
    Gate,
    cbor_decode_one,
    decode_record,
    decode_session,
    interpolate,
    records_from_hex_capture,
    records_from_length_prefixed_stream,
    rsrp_idx_to_dbm,
    rsrq_idx_to_db,
    wifi_frequency_mhz,
)

FIXTURES = pathlib.Path(__file__).resolve().parent / "fixtures"


def load_fixture(name: str) -> bytes:
    return (FIXTURES / f"{name}_v1.cbor").read_bytes()


def load_expected(name: str) -> dict:
    return json.loads((FIXTURES / f"{name}_v1.expected.json").read_text())


class TestGoldenFiles(unittest.TestCase):
    """CP4's acceptance: fixture CBOR decodes to the expected JSON, byte for byte."""

    def test_record_matches_golden_json(self) -> None:
        self.assertEqual(decode_record(load_fixture("record")), load_expected("record"))

    def test_session_matches_golden_json(self) -> None:
        self.assertEqual(decode_session(load_fixture("session")), load_expected("session"))

    def test_fixture_is_the_measured_size(self) -> None:
        # FW-5 budgets 700 B. The firmware test asserts this too; repeating it here
        # catches a fixture regenerated from a schema that quietly outgrew the budget.
        self.assertLessEqual(len(load_fixture("record")), 700)


class TestRecordValues(unittest.TestCase):
    """Specific values, cross-checked against what the firmware test encoded."""

    def setUp(self) -> None:
        self.rec = decode_record(load_fixture("record"))

    def test_header_fields(self) -> None:
        self.assertEqual(self.rec["version"], 1)
        self.assertEqual(self.rec["sequence"], 42)
        self.assertEqual(self.rec["profile"], "DEEP")
        self.assertEqual(self.rec["timeBase"], "unix")
        self.assertEqual(self.rec["tBase"], 1786140992000)
        self.assertEqual(self.rec["networkMode"], "LTE-M")

    def test_position_survives_at_schema_precision(self) -> None:
        # 1e-7 degrees is ~11 mm, far finer than GNSS accuracy, so the scaled integer
        # must round-trip exactly rather than approximately.
        self.assertAlmostEqual(self.rec["gnssBefore"]["lat"], 37.7712317, places=7)
        self.assertAlmostEqual(self.rec["gnssBefore"]["lon"], -122.4310404, places=7)
        self.assertAlmostEqual(self.rec["gnssBefore"]["acc"], 18.3, places=3)

    def test_negative_longitude_is_not_mangled(self) -> None:
        self.assertLess(self.rec["gnssBefore"]["lon"], 0)

    def test_pvt_derived_fields(self) -> None:
        fix = self.rec["gnssBefore"]
        self.assertAlmostEqual(fix["alt"], 25.0, places=3)
        self.assertAlmostEqual(fix["spd"], 31.25, places=3)
        self.assertAlmostEqual(fix["hdg"], 275.5, places=2)
        self.assertEqual(fix["satsUsed"], 6)

    def test_counts_survive(self) -> None:
        # One serving cell plus three GCI cells, ten neighbours, ten APs.
        self.assertEqual(len(self.rec["lte"]), 4)
        self.assertEqual(len(self.rec["lte"][0]["nmr"]), 10)
        self.assertEqual(len(self.rec["wifi"]["accessPoints"]), 10)

    def test_serving_cell_identity(self) -> None:
        serving = self.rec["lte"][0]
        self.assertEqual(serving["eci"], 21414146)
        self.assertEqual(serving["mcc"], 310)
        self.assertEqual(serving["mnc"], 260)
        self.assertEqual(serving["tac"], 14453)
        self.assertEqual(serving["earfcn"], 2300)

    def test_rsrp_and_rsrq_are_converted_from_indices(self) -> None:
        serving = self.rec["lte"][0]
        # Index 54 and 19 are what the modem reported; dBm/dB is what analysis wants.
        # Both are emitted so a suspect conversion can be checked against the raw value.
        self.assertEqual(serving["rsrpIndex"], 54)
        self.assertEqual(serving["rsrp"], -87)
        self.assertEqual(serving["rsrqIndex"], 19)
        self.assertEqual(serving["rsrq"], -10.5)

    def test_mac_is_rendered_from_six_raw_bytes(self) -> None:
        ap = self.rec["wifi"]["accessPoints"][0]
        self.assertEqual(ap["macAddress"], "94:2a:6f:c4:48:00")

    def test_wifi_frequency_is_derived_not_stored(self) -> None:
        ap = self.rec["wifi"]["accessPoints"][0]
        self.assertEqual(ap["channel"], 116)
        self.assertEqual(ap["band"], "5GHz")
        self.assertEqual(ap["frequency"], 5580)

    def test_offsets_survive(self) -> None:
        self.assertEqual(self.rec["offsets"], {
            "cellStartMs": 120,
            "cellEndMs": 4700,
            "wifiStartMs": 130,
            "wifiEndMs": 4650,
            "gnssAfterMs": 6800,
        })

    def test_unmeasured_timing_advance_is_absent_not_zero(self) -> None:
        # This is the assertion the whole "absent, not zero" discipline exists for: the
        # modem reported no timing advance, and 0 is a legitimate reading, so the key
        # must not appear at all.
        for cell in self.rec["lte"]:
            self.assertNotIn("adv", cell)


class TestVersionDispatch(unittest.TestCase):
    """FW-5/HOST-1: fail loudly on an unknown version rather than guessing."""

    def test_unknown_record_version_is_refused(self) -> None:
        # Version 99 with an otherwise well-formed body.
        blob = bytes.fromhex("bf" "0118 63" "0201" "0300" "0400" "0500" "ff".replace(" ", ""))
        with self.assertRaises(ValueError) as ctx:
            decode_record(blob)
        self.assertIn("unsupported record schema version", str(ctx.exception))

    def test_unknown_session_version_is_refused(self) -> None:
        blob = bytes.fromhex("bf" "011863" "026161" "036161" "046161" "ff")
        with self.assertRaises(ValueError):
            decode_session(blob)

    def test_missing_version_is_refused(self) -> None:
        with self.assertRaises(ValueError):
            decode_record(bytes.fromhex("bf0201ff"))


class TestCborReader(unittest.TestCase):
    """The reader only needs the schema's subset, but must be strict about the rest."""

    def test_indefinite_map(self) -> None:
        # zcbor writes every map this way: 0xBF ... 0xFF with no count.
        self.assertEqual(cbor_decode_one(bytes.fromhex("bf01020304ff")), {1: 2, 3: 4})

    def test_map_with_a_dangling_key_is_an_error(self) -> None:
        # A break where a value belongs means the record was cut mid-pair.
        with self.assertRaises(CborError):
            cbor_decode_one(bytes.fromhex("bf010203ff"))

    def test_definite_map(self) -> None:
        self.assertEqual(cbor_decode_one(bytes.fromhex("a201020304")), {1: 2, 3: 4})

    def test_indefinite_array(self) -> None:
        self.assertEqual(cbor_decode_one(bytes.fromhex("9f010203ff")), [1, 2, 3])

    def test_definite_array(self) -> None:
        self.assertEqual(cbor_decode_one(bytes.fromhex("83010203")), [1, 2, 3])

    def test_negative_integers(self) -> None:
        self.assertEqual(cbor_decode_one(bytes.fromhex("20")), -1)
        self.assertEqual(cbor_decode_one(bytes.fromhex("3a48f97e83")), -1224310404)

    def test_byte_and_text_strings(self) -> None:
        self.assertEqual(cbor_decode_one(bytes.fromhex("46942a6fc44800")),
                         bytes.fromhex("942a6fc44800"))
        self.assertEqual(cbor_decode_one(bytes.fromhex("65312e352e34")), "1.5.4")

    def test_truncated_input_is_an_error(self) -> None:
        with self.assertRaises(CborError):
            cbor_decode_one(bytes.fromhex("bf0102"))

    def test_trailing_bytes_are_an_error(self) -> None:
        # Silently ignoring trailing bytes would hide a framing bug at CP8.
        with self.assertRaises(CborError):
            cbor_decode_one(bytes.fromhex("01" "02"))

    def test_unterminated_indefinite_array_is_an_error(self) -> None:
        with self.assertRaises(CborError):
            cbor_decode_one(bytes.fromhex("9f0102"))


class TestConversions(unittest.TestCase):
    """These mirror survey_obs.c; a divergence here silently corrupts every dataset."""

    def test_rsrp_index_to_dbm(self) -> None:
        self.assertEqual(rsrp_idx_to_dbm(0), -141)
        self.assertEqual(rsrp_idx_to_dbm(55), -86)
        self.assertEqual(rsrp_idx_to_dbm(-1), -141)

    def test_rsrq_index_to_db(self) -> None:
        self.assertEqual(rsrq_idx_to_db(30), -5.0)
        self.assertEqual(rsrq_idx_to_db(34), -3.0)
        self.assertEqual(rsrq_idx_to_db(35), -3.0)
        self.assertEqual(rsrq_idx_to_db(-1), -20.0)

    def test_wifi_frequency_2_4_ghz(self) -> None:
        self.assertEqual(wifi_frequency_mhz(0, 1), 2412)
        self.assertEqual(wifi_frequency_mhz(0, 6), 2437)
        self.assertEqual(wifi_frequency_mhz(0, 11), 2462)
        self.assertEqual(wifi_frequency_mhz(0, 14), 2484)

    def test_wifi_frequency_5_ghz(self) -> None:
        self.assertEqual(wifi_frequency_mhz(1, 36), 5180)
        self.assertEqual(wifi_frequency_mhz(1, 116), 5580)

    def test_wifi_frequency_6_ghz(self) -> None:
        self.assertEqual(wifi_frequency_mhz(2, 2), 5935)
        self.assertEqual(wifi_frequency_mhz(2, 1), 5955)

    def test_out_of_range_pair_yields_no_frequency(self) -> None:
        # Fabricating a frequency here would put a plausible wrong number into analysis.
        self.assertIsNone(wifi_frequency_mhz(0, 99))
        self.assertIsNone(wifi_frequency_mhz(1, 5))
        self.assertIsNone(wifi_frequency_mhz(9, 6))


class TestInterpolation(unittest.TestCase):
    def test_midpoint_lies_between_the_brackets(self) -> None:
        rec = interpolate(decode_record(load_fixture("record")))
        interp = rec["interpolated"]
        before = rec["gnssBefore"]["lat"]
        after = rec["gnssAfter"]["lat"]
        self.assertGreater(interp["lat"], before)
        self.assertLess(interp["lat"], after)
        # Scan spans 120..4700 ms, so the midpoint is 2410 ms.
        self.assertEqual(interp["atMs"], 2410.0)

    def test_raw_brackets_are_retained(self) -> None:
        # HOST-1 is explicit: the interpolated value never replaces the measurements.
        rec = interpolate(decode_record(load_fixture("record")))
        self.assertIn("gnssBefore", rec)
        self.assertIn("gnssAfter", rec)

    def test_uncertainty_grows_with_speed(self) -> None:
        rec = decode_record(load_fixture("record"))
        rec["gnssBefore"]["spd"] = rec["gnssAfter"]["spd"] = 1.0
        slow = interpolate(dict(rec))["interpolated"]["interp_uncertainty_m"]
        rec["gnssBefore"]["spd"] = rec["gnssAfter"]["spd"] = 10.0
        fast = interpolate(dict(rec))["interpolated"]["interp_uncertainty_m"]
        self.assertAlmostEqual(fast, slow * 10.0, places=6)

    def test_missing_bracket_is_not_interpolated(self) -> None:
        rec = decode_record(load_fixture("record"))
        del rec["gnssAfter"]
        self.assertNotIn("interpolated", interpolate(rec))

    def test_missing_scan_window_is_not_interpolated(self) -> None:
        rec = decode_record(load_fixture("record"))
        del rec["offsets"]
        self.assertNotIn("interpolated", interpolate(rec))


class TestQualityGate(unittest.TestCase):
    def setUp(self) -> None:
        self.rec = interpolate(decode_record(load_fixture("record")))

    def test_clean_record_passes(self) -> None:
        gate = Gate(max_acc_m=100.0, max_interp_uncertainty_m=1000.0)
        self.assertEqual(gate.reasons(self.rec), [])

    def test_uptime_timebase_is_flagged(self) -> None:
        self.rec["timeBase"] = "uptime"
        self.assertIn("uptime_timebase", Gate().reasons(self.rec))

    def test_uptime_can_be_allowed(self) -> None:
        self.rec["timeBase"] = "uptime"
        gate = Gate(allow_uptime=True, max_interp_uncertainty_m=1000.0)
        self.assertEqual(gate.reasons(self.rec), [])

    def test_missing_bracket_is_flagged(self) -> None:
        del self.rec["gnssAfter"]
        self.assertIn("missing_bracket", Gate().reasons(self.rec))

    def test_poor_accuracy_is_flagged(self) -> None:
        self.rec["gnssBefore"]["acc"] = 250.0
        self.assertIn("poor_gnss_accuracy", Gate().reasons(self.rec))

    def test_excessive_interpolation_uncertainty_is_flagged(self) -> None:
        gate = Gate(max_interp_uncertainty_m=1.0)
        self.assertIn("excessive_interp_uncertainty", gate.reasons(self.rec))


class TestHexCapture(unittest.TestCase):
    """Reads what "survey hex" prints on the console, unedited."""

    def test_extracts_a_block_from_surrounding_noise(self) -> None:
        blob = load_fixture("record")
        capture = (
            "uart:~$ survey hex\r\n"
            f"survey record: {len(blob)} bytes, schema version 1\r\n"
            "-----BEGIN SURVEY RECORD-----\r\n"
            + "\r\n".join(blob.hex()[i:i + 64] for i in range(0, len(blob.hex()), 64))
            + "\r\n-----END SURVEY RECORD-----\r\n"
            "uart:~$ \r\n"
        )
        found = records_from_hex_capture(capture)
        self.assertEqual(len(found), 1)
        self.assertEqual(found[0], blob)
        self.assertEqual(decode_record(found[0])["sequence"], 42)

    def test_capture_without_a_block_is_an_error(self) -> None:
        with self.assertRaises(ValueError):
            records_from_hex_capture("uart:~$ survey show\r\nnothing here\r\n")

    def test_truncated_capture_raises_rather_than_returning_garbage(self) -> None:
        # The normal field failure: the terminal dropped bytes mid-dump. Half a record
        # decoded as if whole would be worse than no record.
        blob = load_fixture("record")
        capture = (
            "-----BEGIN SURVEY RECORD-----\r\n"
            + blob.hex()[:127]
            + "\r\n-----END SURVEY RECORD-----\r\n"
        )
        with self.assertRaises(ValueError):
            records_from_hex_capture(capture)


class TestLengthPrefixedStream(unittest.TestCase):
    """CP8's export framing: scripts/survey_export.py's binary output."""

    def test_splits_multiple_records(self) -> None:
        blob = load_fixture("record")
        stream = struct.pack("<I", len(blob)) + blob + struct.pack("<I", len(blob)) + blob
        found = records_from_length_prefixed_stream(stream)
        self.assertEqual(found, [blob, blob])

    def test_empty_stream_is_zero_records(self) -> None:
        self.assertEqual(records_from_length_prefixed_stream(b""), [])

    def test_short_length_prefix_is_an_error(self) -> None:
        with self.assertRaises(ValueError):
            records_from_length_prefixed_stream(b"\x01\x02\x03")

    def test_declared_length_past_end_of_buffer_is_an_error(self) -> None:
        with self.assertRaises(ValueError):
            records_from_length_prefixed_stream(struct.pack("<I", 100) + b"short")

    def test_zero_length_record_is_an_error(self) -> None:
        with self.assertRaises(ValueError):
            records_from_length_prefixed_stream(struct.pack("<I", 0))


class TestMalformedInput(unittest.TestCase):
    """A corrupted capture must produce a reportable error, never a traceback."""

    def test_top_level_non_map_is_a_cbor_error(self) -> None:
        # 0x01 is a bare integer: valid CBOR, not a record.
        with self.assertRaises(CborError):
            decode_record(b"\x01")

    def test_top_level_array_is_a_cbor_error(self) -> None:
        with self.assertRaises(CborError):
            decode_record(bytes([0x9F, 0x01, 0xFF]))

    def test_session_rejects_a_non_map_too(self) -> None:
        with self.assertRaises(CborError):
            decode_session(b"\x01")


class TestSignedSignalIndices(unittest.TestCase):
    """The 3GPP indices go negative at the weak end, which is where a survey lives.

    RSRP is -17..97 and RSRQ -30..46 per lte_lc.h. These were unsigned in the schema
    once, which did not clip the value -- it failed the encode and discarded the whole
    record. The firmware round-trip test covers the encode side; this covers the decode.
    """

    def test_negative_rsrp_converts(self) -> None:
        # Bottom of the range. Mirrors RSRP_IDX_TO_DBM, which is idx - 140.
        self.assertEqual(rsrp_idx_to_dbm(-17), -157)

    def test_negative_rsrq_converts(self) -> None:
        # Bottom of the range. Mirrors RSRQ_IDX_TO_DB, which is idx/2 - 19.5.
        self.assertEqual(rsrq_idx_to_db(-30), -34.5)

    def test_negative_index_survives_a_decode(self) -> None:
        raw = {
            1: 1, 2: 1, 3: 0, 4: 2, 5: 1786140992000,
            13: {1: 21414146, 2: 310, 3: 260, 4: 14453, 6: -17, 7: -30},
        }
        cell = decode_record(raw)["lte"][0]
        self.assertEqual(cell["rsrp"], -157)
        self.assertEqual(cell["rsrq"], -34.5)


class TestAbsentFields(unittest.TestCase):
    def test_absent_time_diff_is_omitted_not_zero(self) -> None:
        # LTE_LC_CELL_TIME_DIFF_INVALID is 0, so the firmware omits the key entirely. A
        # decoder that defaulted it to 0 would report perfect alignment for a neighbour
        # the modem could not align at all.
        raw = {
            1: 1, 2: 1, 3: 0, 4: 2, 5: 1786140992000,
            14: [{1: 101, 2: 650, 3: 60, 4: 21}],
        }
        nmr = decode_record(raw)["lte"][0]["nmr"][0]
        self.assertNotIn("timeDiff", nmr)

    def test_present_time_diff_is_kept(self) -> None:
        raw = {
            1: 1, 2: 1, 3: 0, 4: 2, 5: 1786140992000,
            14: [{1: 101, 2: 650, 3: 60, 4: 21, 5: 32}],
        }
        nmr = decode_record(raw)["lte"][0]["nmr"][0]
        self.assertEqual(nmr["timeDiff"], 32)


class TestDroppedApCount(unittest.TestCase):
    """Key 18 records how many APs the BSSID filter removed before the scan was stored.

    It matters downstream because the filter is destructive: the unfiltered scan exists
    only for the lifetime of one zbus callback. Without this count a train carriage where
    two thirds of the APs were phone hotspots and a quiet lab where none were look
    identical in the dataset, and the AP density of the survey is unexplainable.
    """

    def test_count_decodes_from_the_fixture(self) -> None:
        self.assertEqual(decode_record(load_fixture("record"))["wifi"]["apDropped"], 7)

    def test_absent_key_omits_it_rather_than_reporting_zero(self) -> None:
        # The key is optional and was added after the first records were captured, so
        # absent means "unknown" -- for a pre-filter record it is not the same claim as
        # "nothing was dropped", and reporting 0 would fabricate the difference away.
        raw = {
            1: 1, 2: 1, 3: 0, 4: 2, 5: 1786140992000,
            16: [{1: bytes.fromhex("942a6fc44800"), 2: -40, 3: 1, 4: 116}],
        }
        self.assertNotIn("apDropped", decode_record(raw)["wifi"])

    def test_count_survives_without_any_surviving_ap(self) -> None:
        # Every AP in range was randomised. The scan list is empty but the record still
        # has to say the radio saw something, otherwise it reads as "no Wi-Fi coverage".
        raw = {1: 1, 2: 1, 3: 0, 4: 2, 5: 1786140992000, 18: 4}
        self.assertEqual(decode_record(raw)["wifi"]["apDropped"], 4)

    def test_wifi_always_carries_an_ap_list_even_when_all_were_dropped(self) -> None:
        # Before key 18 existed, key 16 was the only thing that created wifi[], so
        # "wifi" in rec implied rec["wifi"]["accessPoints"]. A consumer that iterates
        # the list would otherwise raise KeyError on precisely the drop-everything
        # record, which is the one it most wants to look at.
        raw = {1: 1, 2: 1, 3: 0, 4: 2, 5: 1786140992000, 18: 4}
        self.assertEqual(decode_record(raw)["wifi"]["accessPoints"], [])

    def test_a_present_ap_list_is_not_replaced_by_the_default(self) -> None:
        raw = {
            1: 1, 2: 1, 3: 0, 4: 2, 5: 1786140992000,
            16: [{1: bytes.fromhex("942a6fc44800"), 2: -40, 3: 1, 4: 116}],
            18: 4,
        }
        wifi = decode_record(raw)["wifi"]
        self.assertEqual(len(wifi["accessPoints"]), 1)
        self.assertEqual(wifi["apDropped"], 4)


class TestInterpolationEdges(unittest.TestCase):
    def test_zero_bracket_gap_is_not_interpolated(self) -> None:
        # Both fixes at the same instant. Dividing by it would raise; treating it as
        # "absent" would hide a real inconsistency in the record.
        rec = decode_record(load_fixture("record"))
        rec["offsets"]["gnssAfterMs"] = 0
        out = interpolate(rec)
        self.assertNotIn("interpolated", out)
        self.assertEqual(out["interp_skipped"], "non_positive_bracket_gap")

    def test_negative_bracket_gap_is_not_extrapolated_backwards(self) -> None:
        rec = decode_record(load_fixture("record"))
        rec["offsets"]["gnssAfterMs"] = -500
        self.assertNotIn("interpolated", interpolate(rec))


class TestGateReasonNaming(unittest.TestCase):
    def test_unset_timebase_is_named_for_what_it_is(self) -> None:
        # "unset" means nothing ever timestamped the cycle -- a different fault from a
        # clock that ran unsynchronised, and the drop report should say which.
        rec = interpolate(decode_record(load_fixture("record")))
        rec["timeBase"] = "unset"
        self.assertIn("unset_timebase", Gate().reasons(rec))


if __name__ == "__main__":
    unittest.main()
