# Copyright (c) 2024 Nordic Semiconductor
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause

manifest:
  self:
    west-commands: scripts/west-commands.yml
    path: project

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: memfault
      url-base: https://github.com/memfault

  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: main
      import: true
    - name: memfault-firmware-sdk
      remote: memfault
      repo-path: memfault-firmware-sdk
      revision: gminn/1.35.0+coap-conn-id-sharing

