/*
 * Copyright (c) 2025 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

#ifndef _LOCATION_H_
#define _LOCATION_H_

#include <zephyr/kernel.h>
#include <zephyr/zbus/zbus.h>
#include <modem/location.h>
#include <nrf_modem_gnss.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Channels provided by this module */
ZBUS_CHAN_DECLARE(
	location_chan
);

#define MAC_ADDR_LEN 6

enum location_msg_type {
	/* Output message types */

	/* A location search operation has been initiated and is now active. */
	LOCATION_SEARCH_STARTED = 0x1,

	/* A location search operation has completed successfully or due to timeout/error.
	 * This message indicates that the location module has returned to an inactive state
	 * and is ready to accept new location requests.
	 */
	LOCATION_SEARCH_DONE,

	/* A cloud location request with cellular and/or Wi-Fi scanning data is available
	 * for external processing. The cloud request data is found in the .cloud_request
	 * field of the message.
	 */
	LOCATION_CLOUD_REQUEST,

	/* A request for A-GNSS (Assisted GNSS) data has been generated by the GNSS subsystem.
	 * The A-GNSS request parameters are found in the .agnss_request field of the message.
	 * The application should obtain the requested data and provide it back to the
	 * location subsystem.
	 */
	LOCATION_AGNSS_REQUEST,

	/* GNSS location data has been successfully obtained. The location data is found in
	 * the .gnss_data field of the message.
	 */
	LOCATION_GNSS_DATA,

	/* Location module is ready to use */
	LOCATION_MODULE_READY,

	/* Input message types */

	/* Request to initiate a location search operation. This will start the configured
	 * location methods (GNSS, Wi-Fi, Cellular) according to the current location
	 * configuration.
	 */
	LOCATION_SEARCH_TRIGGER,

	/* Request a dedicated GNSS-only fix. Unlike LOCATION_SEARCH_TRIGGER, this bypasses
	 * Wi-Fi and cellular methods and only uses GNSS. A successful fix is published as
	 * LOCATION_GNSS_DATA. On failure/timeout, LOCATION_SEARCH_DONE is published.
	 */
	LOCATION_GNSS_SEARCH_TRIGGER,

	/* Request to cancel an ongoing location search operation.
	 *
	 * WARNING: This operation has known limitations and may cause issues with Wi-Fi
	 * scanning operations. Specifically:
	 * - Wi-Fi scans cannot be truly cancelled at the driver level and may continue
	 *   running, potentially causing -EBUSY errors on subsequent location requests
	 * - Race conditions may occur between cancellation and scan completion
	 * - Scan results may be lost if cancellation occurs during result collection
	 *
	 *
	 * Use this operation only when absolutely necessary. Before cancelling:
	 * - Ensure sufficient delay between subsequent location requests to avoid conflicts
	 * - Consider implementing retry logic to handle potential -EBUSY errors
	 * - Be aware that Wi-Fi scan results may be incomplete or lost
	 */
	LOCATION_SEARCH_CANCEL,

	/* Request a scan of the radio environment only: Wi-Fi and cellular, no GNSS.
	 *
	 * LOCATION_SEARCH_TRIGGER cannot be used to obtain cell and Wi-Fi observations,
	 * because the Location library treats its method list as a fallback chain and
	 * stops at the first method that succeeds -- with the default list a GNSS fix
	 * ends the request before any scan is performed.
	 *
	 * Wi-Fi and cellular are placed next to each other in the method list, which the
	 * Location library combines into a single cloud request carrying both, published
	 * as LOCATION_CLOUD_REQUEST. On failure/timeout, LOCATION_SEARCH_DONE is
	 * published.
	 */
	LOCATION_SCAN_SEARCH_TRIGGER,
};

/** Wi-Fi access point information. */
struct location_wifi_ap_info {
	/** Received Signal Strength Indicator (RSSI) in dBm. */
	int8_t rssi;

	/** MAC address of the Wi-Fi access point. */
	uint8_t mac[MAC_ADDR_LEN];

	/** Length of the MAC address. */
	uint8_t mac_length;
};

/** Cell information.
 *  See lte_lc.h for detailed field descriptions and value ranges.
 */
struct location_cell_info {
	/** E-UTRAN cell ID */
	uint32_t id;

	/** Mobile Country Code */
	int mcc;

	/** Mobile Network Code */
	int mnc;

	/** Tracking Area Code */
	uint32_t tac;

	/** Timing advance */
	uint16_t timing_advance;

	/** EARFCN */
	uint32_t earfcn;

	/** Reference Signal Received Power */
	int16_t rsrp;

	/** Reference Signal Received Quality */
	int16_t rsrq;
};

/** Neighbor cell information.
 *  See lte_lc.h for detailed field descriptions and value ranges.
 */
struct location_neighbor_cell_info {
	/** EARFCN per 3GPP TS 36.101. */
	uint32_t earfcn;

	/** Time difference */
	int time_diff;

	/** Physical Cell ID. */
	uint16_t phys_cell_id;

	/** Reference Signal Received Power */
	int16_t rsrp;

	/** Reference Signal Received Quality */
	int16_t rsrq;
};

/** Cloud location request data containing cellular and/or Wi-Fi scanning information. */
struct location_cloud_request_data {
	/** Current/serving cell information. */
	struct location_cell_info current_cell;

	/** Number of neighboring cells. */
	uint8_t ncells_count;

	/** Neighboring cell information. */
	struct location_neighbor_cell_info neighbor_cells[CONFIG_APP_LOCATION_NEIGHBOR_CELLS_MAX];

	/** Number of GCI (Global Cell Identity) cells. */
	uint8_t gci_cells_count;

	/** GCI cell information with full cell details. */
	struct location_cell_info gci_cells[CONFIG_APP_LOCATION_NEIGHBOR_CELLS_MAX];

	/** Number of Wi-Fi access points. */
	uint16_t wifi_cnt;

	/** Wi-Fi access point information. */
	struct location_wifi_ap_info wifi_aps[CONFIG_APP_LOCATION_WIFI_APS_MAX];
};

/* Structure to pass location data through zbus */
struct location_msg {
	enum location_msg_type type;
	union {
		/** Contains cloud location request data with cellular and/or Wi-Fi information.
		 *  cloud_request is valid for LOCATION_CLOUD_REQUEST events.
		 */
		struct location_cloud_request_data cloud_request;

		/** Contains A-GNSS assistance data request parameters.
		 *  agnss_request is valid for LOCATION_AGNSS_REQUEST events.
		 */
		struct nrf_modem_gnss_agnss_data_frame agnss_request;

		/** Contains GNSS location data including coordinates, accuracy and timing.
		 *  gnss_data is valid for LOCATION_GNSS_DATA events.
		 */
		struct location_data gnss_data;
	};

	/** Timestamp when the sample was taken in milliseconds.
	 *  This is either:
	 * - Unix time in milliseconds if the system clock was synchronized at sampling time, or
	 * - Uptime in milliseconds if the system clock was not synchronized at sampling time.
	 * Only valid for LOCATION_GNSS_DATA events.
	 */
	int64_t timestamp;
};

#ifdef __cplusplus
}
#endif

#endif /* _LOCATION_H_ */
